version: 2

formats: all

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs
      # TODO: I'm not sure why I even use m2r2
      #
      # one of the ugliest hacks I've ever written
      # https://github.com/CrossNox/m2r2/pull/71
      - "sed '13s/nodes, //;611d' $READTHEDOCS_VIRTUALENV_PATH/.venv/lib/python3.13/site-packages/m2r2.py"
    install:
      - "true"


sphinx:
  configuration: docs/api/conf.py
