from typing import Any

import numpy as np
import numpy.typing as npt

def menger_successive(x: npt.NDArray[np.float64], y: npt.NDArray[np.float64], **kwargs: Any) -> int: ...
def menger_anchored(x: npt.NDArray[np.float64], y: npt.NDArray[np.float64], **kwargs: Any) -> int: ...
def double_triangle_area(vertices: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
def get_squared_vector_lengths(vertices: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
def get_curvature(vertices: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
