import enum
from typing import Callable, Tuple

import numpy as np
import numpy.typing as npt

class KneeType(enum.Enum):
    DECREASING_CONVEX = 0
    INCREASING_CONCAVE = 1
    DECREASING_CONCAVE = 2
    INCREASING_CONVEX = 3

def np_windowed(length: int, window_size: int, stride: int = 1, dilation: int = 1) -> npt.NDArray[np.intp]: ...
def np_anchored(length: int) -> npt.NDArray[np.intp]: ...
def prepare(f: Callable[..., int]) -> Callable[..., int]: ...
def normalize(x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
def get_delta_matrix(x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
def get_weight_matrix(x: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
def cubic_spline_smoothing(
    x: npt.NDArray[np.float64], y: npt.NDArray[np.float64], smoothing_factor: float
) -> Tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
def projection_distance(vertices: npt.NDArray[np.float64]) -> npt.NDArray[np.float64]: ...
def detect_knee_type(y1: float, y2: float, y3: float, y4: float) -> KneeType: ...
