name: Test and release job

on:
  push:
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore
    # If you define both branches/branches-ignore and paths/paths-ignore, the workflow will only run when both filters are satisfied.
    branches:
      - "master"
    paths:
      - "./src/knarrow/__about__.py"

jobs:
  build-and-publish:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install hatch
      - run: hatch build
      - name: Publish to pypi.org
        run: hatch publish
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
