name: Build and publish

on:
  push:
    # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore
    # If you define both branches/branches-ignore and paths/paths-ignore, the workflow will only run when both filters are satisfied.
    branches:
      - "master"
    paths:
      - src/knarrow/__about__.py

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # required for OIDC trusted publishing
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@master
      - name: Build
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
