name: Test and release job

# I used to use this (not as good as it spawns extra jobs which cost precious minutes
#on: [push, pull_request]

on:
  push:
    branches:
    - master
    tags:
    - 'v*'
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: |
          3.7
          3.8
          3.9
          3.10
          3.11
    - run: pip install hatch
    - run: hatch run test:cov

  build-and-publish:
    name: Build and publish knarrow
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3.10
        uses: actions/setup-python@master
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
