name: Test and release job

on:
  push:
    branches:
    - master
    tags:
    - 'v*'
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install hatch hatch-vcs
    - run: hatch run +py=${{ matrix.python-version }} lint
    - run: hatch run +py=${{ matrix.python-version }} test:cov
    - run: hatch build
    # TODO add cli tests (somehow)
    - name: Publish to pypi.org
      run: hatch publish
      if: startsWith(github.ref, 'refs/tags')
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
