name: Release a new version of knarrow in PyPI
on: push

jobs:
  build-and-publish:
    name: Build and publish knarrow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3.9
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/